  server:
    port: 8761
  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
    server:
      enableSelfPreservation: true
    instance:
      lease-renewal-interval-in-seconds: 30
